apiVersion: v1
kind: Service
metadata:
  name: sancus-service
spec:
  ports:
    - port: 80
      targetPort: 3000 # Map service port 80 to container port 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: sancus
